server:
  port: 8080

  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=epargne-unite-compte
    username: sa
    password: a123*123
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml


spring:
  datasource:
    url: jdbc:h2:mem:testbd
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true

